# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0012_remove_question_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userqaprofile',
            old_name='points',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='userqaprofile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userqaprofile',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userqaprofile',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
