# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0013_auto_20171024_1245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answervote',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='answervote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answervote',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='questionvote',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='questionvote',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='negative_votes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='positive_votes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='question',
            name='negative_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='positive_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='question',
            name='total_points',
        ),
        migrations.DeleteModel(
            name='AnswerVote',
        ),
        migrations.DeleteModel(
            name='QuestionVote',
        ),
    ]
